### ISSUE TITLE
I cannot get the plugin to work with a library that uses `linaria`

### ISSUE THREAD

**Issue by kuworking** [robwalkerco/gatsby-plugin-compile-es6-packages#10]
I was using this plugin to compile a library (of me) that was written in ES6 and used `@emotion` without any problem (in a Gatsby context)

Now I have migrated the library to `linaria`, and the plugin is not capable of transpiling it correctly (it complains about linaria is used at runtime, which is not allowed)

I have tried to fork the plugin and use it locally in my site, using a `"presets": ["babel-preset-gatsby", "linaria/babel"]` as likely suggested in the docs https://github.com/callstack/linaria/blob/master/docs/CONFIGURATION.md

But it doesn't work, and from the fact that I don't understand webpack enough, I don't know what else I can try

How could I gatsby-transpile an external library that has linaria inside?

*I can use linaria okay within my site

**Comment by robwalkerco** [comment]
Hi @kuworking 
I'm sorry but I can't help you there.
Did you get it working in the end? Is this still an issue with this project, or can this issue be closed?

**Comment by kuworking** [comment]
Hey, no I didn't, I had to discard linaria at the end, so this is no longer a problem (for me at least) so I close the issue

Thanks :)
